version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "TravelManager"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-x2hc1dxfc05z"
s3_prefix = "TravelManager"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
